### PR TITLE
[Validator] Add mime type spoofing detector (#195)

### PR DESCRIPTION
**Pull request by Mth0158**
This PR will require you to update to Rails 6.1.4 (was 6.1.3 before). This due to the fact that Marcel 0.3 is a dependy of Rails 6.1.3 and Marcel 1.0 is a dependency of Rails 6.1.4.

For this PR to work properly (ie accept closely related content type as a match), we need Marcel 1.0.

### CODE REVIEW

**Comment by Mth0158** [comment]
@igorkasyanchuk & @gr8bit what do you think of this PR? :)

**Comment by valscion** [comment]
Really nice work! I do agree that having this as a default is a sensible decision.

However, I'm not sure how many projects are currently relying on this gem already. This change in default functionality is quite big so I'd suggest shipping this change in two parts:

1. First in a 1.x release with the spoofing detection turned off
2. Then a new 2.x major release with the spoofing detection turned on

If you'd like to, you could also ignore doing a 1.x release and ship this directly to a 2.x release. I'd still encourage you to release this as a major version change as this could have subtle and surprising errors pop up for people's projects.

**Comment by Mth0158** [comment]
@valscion thanks for taking time to answer!

> First in a 1.x release with the spoofing detection turned off
> Then a new 2.x major release with the spoofing detection turned on

I do agree with you, I will update the PR to reflect these changes. We will release a v2 with the spoofing protection as default.

**Review by igorkasyanchuk — APPROVED** [review]

**Comment by MaksJS** [comment]
I've tried the new spoofing detection feature. Very nice work.

Unfortunately, I get an exception:

```
      NoMethodError:
        undefined method `attachable' for nil
```

when trying to update a record after creation. It's due to this line:

`@record.attachment_changes[@attribute.to_s].attachable`

After the first record save, when calling `update!` on the same record for example, `@record.attachment_changes` is empty (`{}`).

**Pull request merged**
