### PR TITLE
Fix no implicit conversion of StringIO into String

### PR DESCRIPTION
**Pull request by kwent**
Fix https://github.com/igorkasyanchuk/active_storage_validations/issues/89

Supporting this:

```ruby
   user_avatar = "https://img.favpng.com/17/19/1/business-google-account-organization-service-png-favpng-sUuKmS4aDNRzxDKx8kJciXdFp.jpg"
    filename = File.basename(URI.parse(user_avatar).path)
    file = URI.parse(user_avatar).open
    @user.avatar.attach(io: file, filename: filename) # need to be square ratio
```

### CODE REVIEW

**Comment by igorkasyanchuk** [comment]
@kwent nice, but please check build errors :)

**Comment by kwent** [comment]
Ugh might need some help... had many attempts without sucess

**Comment by igorkasyanchuk** [comment]
@kwent any plans on this PR?

**Comment by kwent** [comment]
I don't unfortunately

**Comment by igorkasyanchuk** [comment]
Np, thanks for trying

**Pull request closed without merging**
