### PR TITLE
preparing a fix for Rails 6 RC 1

### PR DESCRIPTION
**Pull request by igorkasyanchuk**

### CODE REVIEW

**Comment by igorkasyanchuk** [comment]
known issue: 
Error:
ActiveStorageValidations::Test#test_validates:
NoMethodError: undefined method `attachable' for #<ActiveStorage::Attached::Changes::CreateMany:0x00000000053a9d78>
Did you mean?  attachables

but should work for has_one

**Comment by igorkasyanchuk** [comment]
PS: the code is not perfect, the main goal, for now, to make it works and verify on real projects

**Comment by mariebrigitte1** [comment]
cc

**Comment by igorkasyanchuk** [comment]
@mariebrigitte1 what? Conflicts are OK. This branch is for rails 6 only

**Pull request merged**
