### PR TITLE
Add vips support for aspect ratio and dimension validators

### PR DESCRIPTION
**Pull request by NARKOZ**
Vips is a default variant processor [since Rails 7](https://github.com/rails/rails/pull/42744) so it makes sense to support it.

### CODE REVIEW

**Comment by igorkasyanchuk** [comment]
@NARKOZ please update the branch, I'd some conflicts which I tried to resolve but unsuccessfully I think

after that I'll merge, sorry for delays just because of current situation in Ukraine its more difficult to find time

**Comment by NARKOZ** [comment]
@igorkasyanchuk done. 

I'm also from Ukraine 🇺🇦 ✊

**Comment by igorkasyanchuk** [comment]
merged 👍 👍 👍

**Comment by igorkasyanchuk** [comment]
released active_storage_validations-0.9.7.gem

**Pull request merged**
