### PR TITLE
Created AspectRatioValidatorMatcher

### PR DESCRIPTION
**Pull request by maycowmeira**

### CODE REVIEW

**Comment by maycowmeira** [comment]
@igorkasyanchuk sure . Thanks. It still is a work is progress sorry. Is there a label for that?

**Comment by igorkasyanchuk** [comment]
labels no. I just see that specs are failed in github actions

**Comment by igorkasyanchuk** [comment]
Oh) just put any applicable

**Comment by igorkasyanchuk** [comment]
@maycowmeira any plans on this PR? :)

**Comment by maycowmeira** [comment]
> 

Hey Igor ^^. I was kind busy last months changing companies, but I'll get back to it ASAP.

**Comment by Mth0158** [comment]
Hi @maycowmeira,
I am a gem maintainer, I like you PR that implements the `AspectRatioValidatorMatcher`, and I would like to merge it soon.
There have been some changes in the internal of the gem, notably refactoring using concerns, before merging it I would like your PR to use the new structur we are using.
To achieve this, you can refactor your code OR I can add a commit to your work, let me know what you prefer so we can proceed to the next steps! :)

**Comment by maycowmeira** [comment]
> Hi @maycowmeira, I am a gem maintainer, I like your PR that implements the `AspectRatioValidatorMatcher`, and I would like to merge it soon. There have been some changes in the internals of the gem, notably refactoring using concerns + using specs instead of tests, before merging it I would like your PR to use the new structure we are using. To achieve this, you can refactor your code OR I can add a commit to your work, let me know what you prefer so we can proceed to the next steps! :)

Hi @Mth0158 , thanks for contacting. 
If you have time please be my guest to refactor this PR, unfortunately I am not having much time to apply on helping open source 😓 .
Thanks a lot for volunteering

**Pull request merged**
