### PR TITLE
Add dimension validator.

### PR DESCRIPTION
**Pull request by phlegx**
Solves issue #24.

**Examples:**

- Simple dimension validation with `width` and `height`.

```ruby
class User < ApplicationRecord
  has_one_attached :avatar
  has_many_attached :photos

  validates :avatar, dimension: { width: 100, height: 100, message: 'My own message' }
  validates :photos, dimension: { width: 100, height: 100 }
end
```

- Dimension validation with `width`, `height` and `min`, `max`.

```ruby
class User < ApplicationRecord
  has_one_attached :avatar
  has_many_attached :photos

  validates :avatar, dimension: { width: { min: 80 }, height: { min: 80 } }
  validates :photos, dimension: { width: { min: 800, max: 2400 }, height: { min: 600, max: 1800 } }
end
```

- Dimension validation with `width`, `height` and `in`.

```ruby
class User < ApplicationRecord
  has_one_attached :avatar
  has_many_attached :photos

  validates :avatar, dimension: { width: { in: 80..100 }, message: 'My own message' }
  validates :photos, dimension: { height: { in: 600..1800 } }
end
```

- Dimension validation with `min` and `max` range for width and height.

```ruby
class User < ApplicationRecord
  has_one_attached :avatar
  has_many_attached :photos

  validates :avatar, dimension: { min: 200..100 } # width 200, height 100
  # Equivalent to:
  # validates :avatar, dimension: { width: { min: 200 }, height: { min: 100  } }
  validates :photos, dimension: { max: 200..100 } 
  # Equivalent to:
  # validates :avatar, dimension: { width: { max: 200 }, height: { max: 100  } }
end
```

### CODE REVIEW

**Comment by reckerswartz** [comment]
@phlegx great job, can you add test cases?

**Comment by phlegx** [comment]
@reckerswartz no test cases at the moment.

**Comment by reckerswartz** [comment]
Okay, no issues please try to add whenever possible before we make a release, lot of people started using gem in production that's why.

**Comment by phlegx** [comment]
@reckerswartz added tests and examples to docs. Please check PR and release new version if all fine.

**Comment by reckerswartz** [comment]
@phlegx will do it soon. Thanks again.

**Comment by igorkasyanchuk** [comment]
Great job. Please finish PR, add samples and, tests, and I'll merge it in one week. I'm on vacation :)

**Comment by phlegx** [comment]
@igorkasyanchuk thank you. My PR is finished.

**Comment by igorkasyanchuk** [comment]
@phlegx thanks again for contribution. new version of a gem was just released.

**Comment by nezirz** [comment]
Continuously getting error when try to use any type of dimensions validation.
The error:
**ActiveStorage::FileNotFoundError in Devise::RegistrationsController#update**
**ActiveStorage::FileNotFoundError (ActiveStorage::FileNotFoundError):**

My project:
**ruby '2.5.1'
gem 'rails', '~> 6.0.0.rc1'
devise (4.6.2)**

I am trying to validate image dimensions here is my current code try:

```
 has_one_attached :cover_image, dependent: :destroy
  validates :cover_image, size: { less_than: 300.kilobytes , message: 'veličina mora biti manja od 300 kilobajti' },
                            content_type: ['image/png', 'image/jpg', 'image/jpeg'],
                            dimension: { min: 200..100 }

```
I also tried other sample of using dimensions validations and getting the same error.

**Pull request merged**
