### PR TITLE
Dynamic exception class

### PR DESCRIPTION
**Pull request by kwent**
## Dynamic exception_class

Related to https://github.com/igorkasyanchuk/active_storage_validations/issues/149

### CODE REVIEW

**Comment by igorkasyanchuk** [comment]
@kwent please check the tests, I think they could be fixed. How to run them locally check in the readme. You are very close with this PR.

**Comment by igorkasyanchuk** [comment]
@kwent please check logs, 
image

and for example here: https://github.com/igorkasyanchuk/active_storage_validations/runs/5752496199?check_suite_focus=true

maybe you set the IMAGE_PROCESSOR=vips locally and run tests, and it might help.

Not sure how else to fix this.

Also maybe this https://github.com/igorkasyanchuk/active_storage_validations/blob/3f4c30ecdef9cfb1aebbdb79b0badba143280e1a/lib/active_storage_validations/metadata.rb#L11 will be helpful.

Anyway tests needs to be fixed to merge this PR

**Comment by kwent** [comment]
@igorkasyanchuk could you return test workflow ? Thank you!

**Comment by kwent** [comment]
@igorkasyanchuk All checks have passed

**Comment by igorkasyanchuk** [comment]
merged 👍

**Pull request merged**
