### PR TITLE
Fix missing block when using valid? method

### PR DESCRIPTION
**Pull request by kukicola**

### CODE REVIEW

**Comment by kukicola** [comment]
Hello @igorkasyanchuk @gr8bit
Today, I wanted to update my app to use `processable_image` validator I've recently added but unfortunately, it's rising error:

```
     LocalJumpError:
       no block given (yield)
     # /Users/kukicola/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/active_storage_validations-1.0.2/lib/active_storage_validations/metadata.rb:93:in `read_image'
```

Not sure why tests didn't fail

**Comment by gr8bit** [comment]
That's strange... I know almost nobody likes this, but could you please add a test for this condition so this error won't have a chance  to reappear in the future? :)

**Comment by kukicola** [comment]
@gr8bit done, tests will fail without `if block_given?`

**Comment by iainbeeston** [comment]
Is it possible to get this merged? I'm getting the same issue with the processable_image validator

**Comment by gr8bit** [comment]
> Is it possible to get this merged? I'm getting the same issue with the processable_image validator

Yes, sorry. I reviewed it tested it and forgot to merge afterwards.

@igorkasyanchuk this should be relevant enough for a gem release as it fixes a common error. :)

**Comment by igorkasyanchuk** [comment]
active_storage_validations-1.0.3.gem released! thanks!

**Pull request merged**
